// made a map with certain amount of zoom
var map = L.map('map', {
  maxZoom: 15,
  minZoom: 13,
  zoomControl: false,
  detectRetina: true
}).setView([47.612833, -122.331739], 12);

// move the zoom control to the top right corner.
new L.Control.Zoom({
  position: 'topright'
}).addTo(map);

// create 3 basemaps
var streets = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
  attribution: 'Basemap &copy; Leaflet for OpenStreetmap',
  detectRetina: true
  });
var satellite = L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
	attribution: 'Basemap &copy; Leaflet for ESRI',
  detectRetina: true
});
var modBasemap = L.tileLayer('tiles/basemap/{z}/{x}/{y}.png', {
  attribution: 'Generated by Jin Ning Huang | Modified Basemap',
  detectRetina: true
}).addTo(map);

// for tile that display the dots of 2018 year
var dot_2018 = L.tileLayer('tiles/2018_dots_tile/{z}/{x}/{y}.png', {
  attribution: 'Generated by XiaoXi Xia | Location of Car Collision (2018)',
  detectRetina: true
});

// for tile that display the dots of 2019 year
var dot_2019 = L.tileLayer('tiles/2019_dots_tile/{z}/{x}/{y}.png', {
  attribution: 'Generated by XiaoXi Xia | Location of Car Collision (2019)',
  detectRetina: true
});

// for tile that display the dots of 2020 year
var dot_2020 = L.tileLayer('tiles/2020_dots_tile/{z}/{x}/{y}.png', {
  attribution: 'Generated by XiaoXi Xia | Location of Car Collision (2020)',
  detectRetina: true
});

// for tile that display the dots of all year
var dot_all = L.tileLayer('tiles/all_year_dots_tile/{z}/{x}/{y}.png', {
  attribution: 'Generated by XiaoXi Xia | Location of Car Collision (All Years)',
  detectRetina: true
});

// for tile that display the heatmaps of 2018 year
var heats_2018 = L.tileLayer('tiles/heatmap_2018/{z}/{x}/{y}.png', {
  attribution: 'Generated by XiaoXi Xia | Heat Location of Car Collision (2018)',
  detectRetina: true
});

// for tile that display the heatmaps of 2019 year
var heats_2019 = L.tileLayer('tiles/heatmap_2019/{z}/{x}/{y}.png', {
  attribution: 'Generated by XiaoXi Xia | Heat Location of Car Collision (2019)',
  detectRetina: true
});

// for tile that display the heatmaps of 2020 year
var heats_2020 = L.tileLayer('tiles/heatmap_2020/{z}/{x}/{y}.png', {
  attribution: 'Generated by XiaoXi Xia | Heat Location of Car Collision (2020)',
  detectRetina: true
});

// for tile that display the heatmaps of all year
var heats_all = L.tileLayer('tiles/heatmap_all_years/{z}/{x}/{y}.png', {
  attribution: 'Generated by XiaoXi Xia | Heat Location of Car Collision (All Years)',
  detectRetina: true
});

// assign the label for the basemaps
var baseLayers = {
  'Streets': streets,
  'Satellite': satellite,
  'Dark Street Network': modBasemap
};

// assign the label for the tiles
var overlays = {
  "2018": dot_2018,
  "2019": dot_2019,
  "2020": dot_2020,
  "All": dot_all,
  "2018 (heat)": heats_2018,
  "2019 (heat)": heats_2019,
  "2020 (heat)": heats_2020,
  "All (heat)": heats_all
}

// add the user control to switch the tiles on the map
L.control.layers(baseLayers, overlays, {
  collapsed: false,
  position: 'topright'
}).addTo(map);

// control panel desc
$(".leaflet-control-layers-overlays").prepend("<label>Please only select <br> <b>one or two</b>.</label>");

// Add a scale bar to map
L.control.scale({position: 'bottomright'}).addTo(map);
